--- 
- name: Apt update
  apt:
    update_cache: yes

- name: Install CMake
  apt: pkg=cmake

- name: Install Unzip
  apt: pkg=unzip

- name: Install Pip
  apt: pkg=python-pip

- name: Install git
  apt: pkg=git

- name: Install Emacs
  apt: pkg=emacs