# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"

  config.vm.network "forwarded_port", guest: 5000, host: 5000
  
  config.vm.synced_folder "../app", "/home/vagrant/app"

  config.vm.provider "virtualbox" do |v|
    v.name = "LILO"
  end
  #
  # Run Ansible from the Vagrant Host
  #
  config.vm.provision "ansible" do |ansible|
  	ansible.playbook = "../ansible/playbook.yml"
    ansible.sudo = true
  end

end
